### ISSUE TITLE
Relaxing the dependency constraint on OCaml

### ISSUE THREAD

**Issue by rauanmayemir** [facebookexperimental/reason-native#71]
Is there any reason OCaml version constrained to `<= 4.7.0`? Why not drop the upper bound altogether?

**Comment by jordwalke** [comment]
I just realized that `<= 4.7.0` is a pretty weird and wrong constraint because why wouldn't it support `4.7.1` if it supports `4.7.0`? I think you're right we want to just remove the upper constraint.

**Comment by rauanmayemir** [comment]
When can we get this in? I want to start using Rely asap. 😄

**Comment by bandersongit** [comment]
I'll test changing the constraint to 4.2.0 (4.4.0 because of some Printexc features we use) today and if all goes well, I'll look to get a new version of Rely out to npm today or tomorrow.

**Comment by bandersongit** [comment]
This has been merged, I just released Rely 1.0.1 which supports Ocaml ^4.4.0. I did not publish new versions for any of the other packages, but we can do that as well.

**Comment by rauanmayemir** [comment]
@bandersongit We'll have to wait for other packages as well, because Rely depends on Pastel and File-context-printer, so it's still locked on `>=4.4.0 <=4.7.0`.

Fyi, `^4.4.0` might still not be the best strategy as `OCaml` doesn't follow semver.

**Comment by bandersongit** [comment]
I'll plan on getting out updated versions of the other packages out by Monday or Tuesday with the current version bounds.

Any thoughts on what we might want to do here with the dependency version? (@jordwalke )

**Comment by bandersongit** [comment]
I just published updated versions of console, pastel, and file-context-printer. You should be good to go now.

I talked with @jordwalke  about the version bound issue and we are fine with the bounds we have for now

**Comment by rauanmayemir** [comment]
@bandersongit I think you forgot to change the OCaml constraint in `console.json`.

**Comment by bandersongit** [comment]
Good call out, @jordwalke already updated the version of ocaml in console.json and I'm bumping the version of console and will publish an update shortly. Hopefully you've been able to use Rely without issues in the meantime.

**Comment by bandersongit** [comment]
Published an updated version of console
